name = Drupal Origins SEO Extension
description = Drupal Origins SEO Extension Drupal Origins SEO Extension Drupal Origins SEO Extension Drupal Origins SEO Extension
core = 7.x

# Core extensions
dependencies[] = block
dependencies[] = comment
dependencies[] = contextual
dependencies[] = help
dependencies[] = image
dependencies[] = list
dependencies[] = menu
dependencies[] = number
dependencies[] = options
dependencies[] = path
dependencies[] = taxonomy
dependencies[] = dblog
dependencies[] = field_ui
dependencies[] = file
dependencies[] = update